# Generated by Django 3.2.5 on 2021-07-07 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210707_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.mood'),
        ),
    ]
